name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.private_key }}
        repository: mathias-luedtke/testpriv
        path: testpriv
    - run: cat testpriv/README.md

  test_no_checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: mathias-luedtke/testpriv
        path: testpriv
      continue-on-error: true
    - run: test ! -e testpriv/README.md

  test_ici:
    runs-on: ubuntu-latest
    steps:
      - uses: 'mathias-luedtke/industrial_ci@feature/github-ssh-key'
        with:
          ssh-key: ${{ secrets.private_key }}
        env:
          ROS_DISTRO: "humble"
          TARGET_WORKSPACE: "git+ssh://git@github.com/mathias-luedtke/testpriv.git#main"

  test_webfactory:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.private_key }}
      - run: sed 's|/home/runner|/root|g' -i.bak ~/.ssh/config
      - uses: 'mathias-luedtke/industrial_ci@feature/github-ssh-key'
        env:
          ROS_DISTRO: "humble"
          TARGET_WORKSPACE: "git+ssh://git@github.com/mathias-luedtke/testpriv.git#main"
